### ISSUE TITLE
Game hangs on opening

### ISSUE THREAD

**Issue by xathian** [fedddddd/tpp-mod#29]
Trying to use tpp-mod to use your custom server mod (Using the hex editing method to change the URL breaks the exe from working). I run the game with the flag and get the cmd window pop up showing everything loading however the game opens to a white screen for about 3 minutes then crashes.

![rXaddXN 1](https://github.com/fedddddd/tpp-mod/assets/4474089/beea9779-04ab-44e0-b681-acb964592a7f)

**Comment by MXYLR** [comment]
I guess you broke the string address while editting them
